---
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.8" ]]; then
      wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-ppc64le.sh -O anaconda.sh;
    else
      wget https://repo.anaconda.com/archive/Anaconda2-2019.10-Linux-ppc64le.sh -O anaconda.sh;
    fi
  - bash anaconda.sh -b -p $HOME/anaconda
  - source "$HOME/anaconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
#  - bash ./config.sh
#  - conda env create --file environment.yml
#  - conda activate ForwardModel
#  - python setup.py install
#- pip install -r requirements.txt
# command to run tests
script:
  - pytest

after_script:
  - source deactivate ForwardModel
...