---
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - bash ./config.sh
  - conda env create --file environment.yml
before_script:
  - source activate ForwardModel
#- pip install -r requirements.txt
# command to run tests
script:
  - pytest

after_script:
  - source deactivate ForwardModel
...