---
os:
  - linux
language: python
python:
  - "3.6"
#  - "3.7"
#  - "3.8"
# command to install dependencies
before_install:
  - sudo apt update
  - link="https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh";
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then #  echo "Linux"
#        link="https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh";
#    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then #   echo "Mac"
#        link="https://repo.anaconda.com/archive/Anaconda3-2020.02-MacOSX-x86_64.sh";
#    fi
  - wget $link -O anaconda.sh;
  - bash anaconda.sh -b -p "$HOME/anaconda"
  - source "$HOME/anaconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create --file environment.yaml
  - conda activate ForwardModel
install:
  - python setup.py install
#- pip install -r requirements.txt
# command to run tests
script:
  - pytest

after_script:
  - source deactivate ForwardModel
...